# Generated by Django 5.2 on 2025-05-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_account_user_alter_account_goals_and_more'),
        ('challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='account_app.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='challenge_app.challenge'),
            preserve_default=False,
        ),
    ]
