# Generated by Django 5.2 on 2025-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0002_answer_account_answer_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(null=True),
        ),
    ]
