# Generated by Django 5.2 on 2025-05-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0004_rename_date_challenge_dateof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='dateOf',
            new_name='date',
        ),
    ]
