# Generated by Django 5.2 on 2025-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0008_challenge_input_challenge_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='solve',
            field=models.BooleanField(default=False),
        ),
    ]
