# Generated by Django 5.2 on 2025-05-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0009_answer_solve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='input',
            new_name='input_J',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='output',
            new_name='input_P',
        ),
        migrations.AddField(
            model_name='challenge',
            name='output_J',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='output_P',
            field=models.CharField(null=True),
        ),
    ]
