# Generated by Django 5.2 on 2025-05-01 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='user_app.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='goals',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='years',
            field=models.IntegerField(null=True),
        ),
    ]
