# Generated by Django 5.2 on 2025-05-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('questionLink', models.CharField(null=True)),
                ('questionTitle', models.CharField(null=True)),
                ('difficulty', models.CharField(null=True)),
                ('question', models.CharField(null=True)),
                ('hints', models.CharField(null=True)),
            ],
        ),
    ]
