# Generated by Django 5.2 on 2025-05-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0005_rename_dateof_challenge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
