# Generated by Django 5.2 on 2025-05-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0006_challenge_html_alter_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='code',
        ),
    ]
