# Generated by Django 5.2 on 2025-05-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0007_rename_text_answer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='input',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='output',
            field=models.CharField(null=True),
        ),
    ]
