# Generated by Django 5.2 on 2025-05-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0010_rename_input_challenge_input_j_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.CharField(null=True),
        ),
    ]
